dashboard/urls.py
from django.urls import path, include

from dashboard import views

app_name = 'dashboard'


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('rendezvous/', views.rendezvous, name='rendezvous'),
    path('dossiers/', views.dossiers, name='dossiers'),
    path('catalogue/', views.catalogue, name='catalogue'),
    path('profil/', views.profil, name='profil'),


    path('diagnostic/<pk>', views.diagnostic, name='diagnostic'),
    path('listeMaladies/<pk>', views.listeMaladies, name='listeMaladies'),
    path('pagefinale/<pk>', views.pagefinale, name='pagefinale'),

    path('nouveauPatient/', views.creer_patient, name='nouveauPatient'),
    path('editPatient/<pk>', views.editPatient, name='editPatient'),
    path('showPatient/<pk>', views.showPatient, name='showPatient'),
    path('nouvelAntecedant/', views.addAntecedant, name='nouvelAntecedant')
]

medicaldiagnosis/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from search.views import synthetiseur, instantSearch
from dashboard.views import detailMaladie


urlpatterns = [

    #Section CSD
    path('dashboard/', include('dashboard.urls')),
    #Fin section CSD

	path('home', views.home_view, name='home'),
    path('admin/', admin.site.urls),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name="logout"),
    path('reset/', views.reset_password_view, name="reset"),
    path('password_change/', views.password_change_view, name="password_change"),
    path('ajax/synthetiseur/', synthetiseur, name='synthetiseur'),
    path('ajax/instantsearch/', instantSearch, name='instantSearch'),
    path('ajax/detailMaladie/', detailMaladie, name='detailMaladie'),
    
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

SITUATION_CHOICES = (
    ('MARIE', 'Marié'),
    ('CELIBATAIRE', 'Célibataire'),
)

#verbose_name permet de gérer l'affichage du champ (le label)
class Personne (models.Model):
	nom = models.CharField(max_length=30, verbose_name='Nom')
	prenom = models.CharField(max_length=30, verbose_name='Prénom')
	tel = models.CharField(max_length=30 ,verbose_name='Téléphone')
	adresse = models.CharField(max_length=50, verbose_name='Adresse')
	dateNaiss = models.CharField(max_length=15 ,verbose_name='Date de naissance')

	class Meta:
		abstract = True

class Medecin (Personne):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	specialite = models.CharField(max_length=20, verbose_name='Spécialité')
	lieuTravail = models.CharField(max_length=20, verbose_name='Lieu de travail')

class Patient (Personne):
	profession = models.CharField(max_length=20, verbose_name='Profession')
	situationMatr = models.CharField(max_length=50, verbose_name="Situation Matrimoniale", choices=SITUATION_CHOICES)
	assurance = models.CharField(max_length=10, verbose_name="Assurance")
	securiteSociale = models.CharField(max_length=13, verbose_name="N° Sécurité sociale")

	def __str__(self):
		return "%s - %s - %s" % (self.prenom, self.nom, self.dateNaiss)

class Consultation (models.Model):
	date = models.DateField(verbose_name='Date de consultation')
	poids = models.FloatField(verbose_name='Poids', null = True)
	temperature = models.FloatField(verbose_name='Température', null = True)
	tension = models.FloatField(verbose_name='Tension', null = True)
	motifs = models.CharField(max_length=500, verbose_name='Motifs', null = True)
	examenClinique = models.CharField(max_length=500, verbose_name='Examen Clinique')
	diagnostic = models.CharField(max_length=100, verbose_name='Diagnostic')

	medecin = models.ForeignKey(Medecin, on_delete=models.DO_NOTHING, null = True, verbose_name='Médecin')
	patient = models.ForeignKey(Patient, on_delete=models.DO_NOTHING, null = True, verbose_name='Patient')

class Antecedant (models.Model):
	nature = models.CharField(max_length=15, verbose_name="Nature de l'antécédent")
	description = models.CharField(max_length=30, verbose_name="Description de l'antécédent")
	
	patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, verbose_name='Patient')


class Symptome (models.Model):
	nomSymptome = models.CharField(max_length=254, unique=True)

	class Meta:
		ordering = ('nomSymptome',) #Les résultats d'une requête devrait être rangé par ordre alphabétique

class Maladie(models.Model):	
	nomMaladie = models.CharField(max_length=254,verbose_name="Nom")
	description = models.TextField(verbose_name="Description")

	symptomes = models.ManyToManyField(Symptome)
	class Meta:
		ordering = ('nomMaladie',)

	def save(self):
		from search.models import MedicalData
		print(self.nomMaladie)
		maladie = MedicalData(nomMaladie = self.nomMaladie, description = self.description)
		maladie.save()
		super().save()

dashboard/forms.py
from django import forms
from .models import *

"""Formulaire créé à partir du modèle Patient de notre application"""
class PatientForm(forms.ModelForm):
	 dateNaiss = forms.DateField(widget=forms.widgets.DateInput(format="%m/%d/%Y", attrs={'type':'date'}))
	 class Meta:
	    model = Patient
	    fields = ('__all__')

class AntecedantForm(forms.ModelForm):
	class Meta:
		model = Antecedant
		fields = ('__all__')

class ConsultationForm(forms.ModelForm):
	class Meta:
		model = Consultation
		fields = ('__all__')

class MedecinForm(forms.ModelForm):
	dateNaiss = forms.DateField(widget=forms.widgets.DateInput(format="%m/%d/%Y", attrs={'type':'date'}))
	class Meta:
	    model = Medecin
	    exclude = ['user']

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Patient
from django.views.decorators.csrf import csrf_protect, csrf_exempt
import search
from .models import Patient, Antecedant, Medecin
from .forms  import PatientForm, AntecedantForm, MedecinForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from search.views import MedicalData
from django.http import JsonResponse

# Create your views here.
@login_required
def dashboard(request):

	return render(request, "dashboard/dashboard.html")

@login_required
def rendezvous(request):

	return render(request, "dashboard/rendezvous.html")

@login_required
def dossiers(request):
	patients = Patient.objects.all().order_by('nom', 'prenom')
	return render(request ,"dashboard/dossiers.html", {'patients' : patients})

#fonction pour lire un patient donné
@login_required
def showPatient(request, pk):
	pk= int(pk) # make sure we have an integer.
	patient = Patient.objects.get(id=pk)
	antecedant = Antecedant.objects.filter(patient=patient)
	return render(request, "dashboard/showPatient.html", {'p': patient, 'antecedant': antecedant})

@login_required
def catalogue(request):

	return render(request, "dashboard/catalogue.html")

@login_required
def profil(request):
	user=request.user
	medecin = get_object_or_404(Medecin, pk=user.id)
	print(medecin.nom)
	if request.method == "POST":
		form = MedecinForm(request.POST, instance=medecin)
		if form.is_valid():
			post = form.save()
			return redirect('http://localhost:8000/dashboard/profil')
	else:
		form = MedecinForm(instance=medecin)
	return render(request, "dashboard/profil.html", {'form': form, 'm': medecin})



@login_required
def diagnostic(request, pk):
	pk= int(pk) # make sure we have an integer.
	patient = Patient.objects.get(id=pk)
	antecedant = Antecedant.objects.filter(patient=patient)
	return render(request, "dashboard/diagnostic.html", {'p': patient, 'antecedant': antecedant})


#vues pour ajouter un patient dans le système et le modifier par la suite
@login_required
def creer_patient(request):
	if request.method == "POST":
		form = PatientForm(request.POST or None)
		if form.is_valid():
			post = form.save()
			return redirect('http://localhost:8000/dashboard/showPatient/{}'.format(post.pk), pk=post.pk)
	else:
		form = PatientForm()
	return render(request, 'dashboard/creer_patient.html', {'form': form})

@login_required
def editPatient(request, pk):
	patient = get_object_or_404(Patient, pk=pk)
	if request.method == "POST":
		form = PatientForm(request.POST, instance = patient)
		if form.is_valid():
			post = form.save()
			return redirect('http://localhost:8000/dashboard/showPatient/{}'.format(post.pk))
	else:
		form = PatientForm(instance=patient)
	return render(request, 'dashboard/creer_patient.html', {'form': form})


@csrf_exempt
def listeMaladies(request, pk):
#	print("here")
#	print("eeee"+request.POST['texte'])

#	pk= int(pk) # make sure we have an integer.
	patient = Patient.objects.get(id=pk)

	listeMaladies = request.POST['texte'].split("-")

	return render(request, "dashboard/listeMaladies.html", {'p': patient, 'listeMaladies': listeMaladies}) 



def pagefinale(request, pk):
	import math

	some_var = request.POST.getlist('checks')
	print(some_var)
	diagnostic = search.views.diagnostic(some_var)
	s = dict()
	d = dict()
	for hit in diagnostic:
		s[hit['_source']['nomMaladie']] = hit['_score']
#		print(hit['_score'], hit['_source']['nomMaladie'])
	maxValue = s[(next(iter(s)))]
	print(maxValue)
	maladie = MedicalData.objects.get(nomMaladie = next(iter(s)))
	print(maladie.nomMaladie, maladie.listeSymptomes)

	cpt = 0
	for i in some_var:
		if i in maladie.listeSymptomes:
			cpt+=1


	coeff = ((cpt/(len(maladie.listeSymptomes.split(','))-1))*100)/maxValue

	for key, value in s.items():
		s[key] = math.ceil(value * coeff)

	for key, value in s.items():
		d[key.capitalize()] = value


	print(d)

	return render(request, "dashboard/pagefinale.html", {'d': d})

def detailMaladie(request):


	maladie = MedicalData.objects.get(nomMaladie = request.GET.get('nomMaladie'))
	details = {'nomMaladie': maladie.nomMaladie.capitalize(), 'description': maladie.description, 'listeSymptomes': maladie.listeSymptomes}
	return JsonResponse(details)

#vues pour ajouter, éditer les antécédents d'un patient
@login_required
def  addAntecedant(request):
	patient = Patient.objects.get(id=request.GET.get('idPatient'))
#	if request.method == "POST":
	nature = request.GET.get('modalNature')
	description = request.GET.get('modalDescription')
	antecedant = Antecedant.objects.create(nature = nature, description = description, patient = patient)
	details = {'nature': antecedant.nature, 'description': antecedant.description}
	return JsonResponse(details)

#maladie = MedicalData.objects.get(nomMaladie = request.GET.get('nomMaladie'))
#details = {'nomMaladie': maladie.nomMaladie.capitalize(), 'description': maladie.description, 'listeSymptomes': maladie.listeSymptomes}
#return JsonResponse(details)

dashboard/templates/dashboard/base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "dashboard/assets/images/favicon.png" %}">
    <title>{% block title %}MedicApp{% endblock %}</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static "dashboard/assets/plugins/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static "dashboard/css/style.css" %}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{% static "dashboard/css/colors/blue.css" %}" id="theme" rel="stylesheet">

    {% block recording %}{% endblock %}



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header fix-sidebar card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-toggleable-sm navbar-light">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="index.html">
                        <!-- Logo icon -->
                        <b>
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <img src="{% static "dashboard/assets/images/logo-icon.png" %}" alt="homepage" class="dark-logo" />
                            
                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text -->
                        <span>
                            <!-- dark Logo text -->
                            <img src="{% static "dashboard/assets/images/logo-text.png" %}" alt="homepage" class="dark-logo" />
                        </span>
                    </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                  
                    {% if user.is_authenticated %}
                    <ul class="navbar-nav mr-auto mt-md-0 ">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                        <li class="nav-item hidden-sm-down">
                            <!-- <form class="app-search p-l-20">
                                <input type="text" class="form-control" placeholder="Search for..."> <a class="srh-btn"><i class="ti-search"></i></a>
                            </form>-->
                        </li>
                    </ul>
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="{% url "dashboard:profil" %}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><a href="{% url "dashboard:profil" %}"><img src="{% static "dashboard/assets/images/users/3.jpg" %}" alt="user" class="profile-pic m-r-5" />{{ user.username }}</a></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li>
                            <a href="{% url "dashboard:dashboard" %}" class="waves-effect"><i class="fa fa-clock-o m-r-10" aria-hidden="true"></i>Tableau de bord</a>
                        </li>
                        <li>
                            <a href="{% url "dashboard:rendezvous" %}" class="waves-effect"><i class="fa fa-table m-r-10" aria-hidden="true"></i>Rendez-vous</a>
                        </li>
                        <li>
                            <a href="{% url "dashboard:dossiers" %}" class="waves-effect"><i class="fa fa-globe m-r-10" aria-hidden="true"></i>Dossiers patients</a>
                        </li>
                        <li>
                            <a href="{% url "dashboard:catalogue" %}" class="waves-effect"><i class="fa fa-columns m-r-10" aria-hidden="true"></i>Catalogue médical</a>
                        </li>
                        <li>
                            <a href="{% url "dashboard:profil" %}" class="waves-effect"><i class="fa fa-user m-r-10" aria-hidden="true"></i>Profil</a>
                        </li>

                        <!--<li>
                            <a href="icon-fontawesome.html" class="waves-effect"><i class="fa fa-font m-r-10" aria-hidden="true"></i>Icons</a>
                        </li>
                        <li>
                            <a href="pages-error-404.html" class="waves-effect"><i class="fa fa-info-circle m-r-10" aria-hidden="true"></i>Error 404</a>
                        </li>-->
                    </ul>
                    <ul id="sidebar" class="logout">
                         <li><a href="{% url 'logout' %}" class="waves-effect"><i class=" fa fa-power-off m-r-10" aria-hidden="true"></i>Déconnexion</a></li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->

         <!-- Block content - CSD -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->

        {% block content %}

        {% endblock %}

        {% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}


         <!-- End block content - CSD -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->

        <!-- footer -->
            <!-- ============================================================== -->
           <!--  <footer class="footer text-center">
                © 2017 Monster Admin by wrappixel.com
            </footer> -->
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->

    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static "dashboard/assets/plugins/jquery/jquery.min.js" %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static "dashboard/assets/plugins/bootstrap/js/tether.min.js" %}"></script>
    <script src="{% static "dashboard/assets/plugins/bootstrap/js/bootstrap.min.js" %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static "dashboard/js/jquery.slimscroll.js" %}"></script>
    <!--Wave Effects -->
    <script src="{% static "dashboard/js/waves.js" %}"></script>
    <!--Menu sidebar -->
    <script src="{% static "dashboard/js/sidebarmenu.js" %}"></script>
    <!--stickey kit -->
    <script src="{% static "dashboard/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js" %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static "dashboard/js/custom.min.js" %}"></script>
    <!-- ============================================================== -->
    <!-- This page plugins -->
    <!-- ============================================================== -->
    <!-- Flot Charts JavaScript -->
    <script src="{% static "dashboard/assets/plugins/flot/jquery.flot.js" %}"></script>
    <script src="{% static "dashboard/assets/plugins/flot.tooltip/js/jquery.flot.tooltip.min.js" %}"></script>
    <script src="{% static "dashboard/js/flot-data.js" %}"></script>
    <script src="{% static "dashboard/js/jquery-ui/jquery-ui.js" %}"></script>
    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="{% static "dashboard/assets/plugins/styleswitcher/jQuery.style.switcher.js" %}"></script>
</body>

</html>

dashboard/templates/dashboard/dossiers.html
{% extends "dashboard/base.html" %}

{% load static %}

{% block title %}Dossiers Patients{% endblock %}

{% block content %}

 <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <div class="row page-titles">
                    <div class="col-md-6 col-8 align-self-center">
                        <h3 class="text-themecolor m-b-0 m-t-0">Dashboard</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>
                        <button class="btn btn-success"> 
                            <a href="{% url "dashboard:nouveauPatient" %}"> Nouveau Patient </a> </button>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-block">
                                <h4 class="card-title">Dossiers Patients</h4>
                                <div class="table-responsive m-t-40">
                                    <table class="table stylish-table">
                                        <thead>
                                            <tr>
                                                <th>Identifiant</th>
                                                <th>Prénom</th>
                                                <th>Nom</th>
                                                <th>Date de Naissance</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for p in patients %} 
                                                <tr>
                                                    <td style="width:50px;"><span class="round">
                                                        <a href="{% url "dashboard:showPatient" pk=p.id %}">
                                                        {{ p.id }}</a>
                                                    </span></td>
                                                    <td>
                                                        <h6> <a href="{% url "dashboard:showPatient" pk=p.id %}"> {{ p.prenom }}</a>
                                                    </h6></td>
                                                    <td>{{ p.nom }}</td>
                                                    <td>{{ p.dateNaiss }}</td>
                                                </tr>
                                            {% endfor %} 
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
   
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->

{% endblock %}

dashboard/templates/dashboard/listeMaladies.html
{% load static %}

<link href="{% static "dashboard/css/listeMaladies.css" %}" id="theme" rel="stylesheet">
<div class="remplacer">
<div class="container-fluid">
	<div class="row">
		<div class="col-6">
	<h3 style="text-decoration: underline;">Symptomes trouvés</h3>


<form action="{% url "dashboard:pagefinale" pk=p.id %}"method="post">
	{% csrf_token %}
	{% for nomMaladie in listeMaladies %}
		<label class="container">{{nomMaladie|capfirst}}
		  <input type="checkbox" name="checks" value="{{nomMaladie}}" id="{{nomMaladie}}" checked="checked">
		  <span class="checkmark"></span>
		</label>
	{% endfor %}
	<button class="btn btn-primary" type="submit">Diagnostiquer</button>
</form>

</div>
<div class="col-6">
		<h3 style="text-decoration: underline;">Autres symptômes et signes cliniques</h3>

			<div class="input-group">
  				<span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></span>
  				<input type="text" class="form-control" placeholder="Recherche" aria-describedby="basic-addon1" id="search">
			</div>
			<select name="resuls" size="10" id="results" style="width: 100% !important; min-width: 100%; max-width: 100%;">
				
			</select>
</div>
</div>
</div>
</div>
<script type="text/javascript">

$("#search").on('input', function () {
      var nomMaladie = $(this).val();

      $.ajax({
        url: '/ajax/instantsearch/',
        data: {
          'nomMaladie': nomMaladie
        },
        dataType: 'json',
        success: function (propositions) {
        	$("#results").empty()
          tab = propositions['propositions'].split('-')
          
      
          for (var i = 0; i < tab.length; i++) {
  				
  				//$('#results').append('<h4><li><a>'+tab[i]+'</a></li></h4>')
  				$('#results').append('<option value="'+tab[i]+'">'+tab[i].charAt(0).toUpperCase()+tab[i].slice(1)+'</option>')
				
			}
        }
      });

    });
	
	$(document).ready(function(){
		var tab = [];
	$("body").on('dblclick', 'option', function() {
  		//alert( this.value );
  		var element = document.getElementById(this.value);
  		
  		if($(element).length == 0 && !tab.includes(this.value)){
  			$( '<label class="container">'+this.value.charAt(0).toUpperCase()+this.value.slice(1)+
	  			'<input type="checkbox" name="checks" value="'+this.value+
	  			'" checked="checked"><span class="checkmark"></span></label>' ).insertBefore( "button" );
  			tab.push(this.value);
  			console.log(tab);
  		}

  		

});
	});

</script>

</div>